linting fix

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -30,8 +30,26 @@ jobs:
       run: |
         sudo npm install
         sudo npm install -g jscpd@3.2.1
+    - name: Static Analysis
+      run: |
+        pylint guardrails/ test/
+        jscpd --min-tokens 20 --reporters "json" --mode "strict" --format "python" -o . .
+        python3 test_resource/jscpd_parser.py --j 10 #Allowed duplication is 10% with 20 token size
+
+    - name: Cyclomatic complexity
+      run: |
+        python3 -m lizard guardrails -X> CC.xml
+        python3 test_resource/cyclo_gate.py --c 10 #Allowed cyclomatic complexity is less than 10
+    - name: Dead Code
+      run: |
+        python3 -m vulture guardrails
     - name: Tests & Coverage
       run: |
-        pytest test -p no:logging --cov-config=.coveragerc --cov=guardrails
+        pytest test --cov-config=.coveragerc --cov=guardrails
         coverage report --fail-under=90 #Coverage should be above 90%
         codecov
+    - name: Mutation Tests
+      run: |
+        mutmut run > mutmut.log || true # Checking mutation on main file as the travis max execution time is overshooting
+        mutmut junitxml --suspicious-policy=ignore --untested-policy=ignore > mutmut.xml
+        python3 test_resource/mutmut_parse.py --m 20 #Mutation (failure+disables+error) allowed 20% of total mutants
